#ifndef YVM_OPTION_H

#define YVM_DEBUG_INTERNAL
#undef YVM_DEBUG_CLASS_FILE
#define YVM_DEBUG_SHOW_EXEC_FLOW
#ifdef YVM_DEBUG_INTERNAL
#undef YVM_DEBUG_SHOW_SIZEOF_ALL_TYPE
#undef YVM_DEBUG_SHOW_BYTECODE
#undef YVM_DEBUG_SHOW_EXEC_FLOW
#endif

#ifdef YVM_DEBUG_CLASS_FILE
#define YVM_DEBUG_SHOW_VERSION
#define YVM_DEBUG_SHOW_CONSTANT_POOL_TABLE
#define YVM_DEBUG_SHOW_INTERFACE
#define YVM_DEBUG_SHOW_CLASS_FIELD
#define YVM_DEBUG_SHOW_CLASS_ACCESS_FLAGS
#define YVM_DEBUG_SHOW_CLASS_METHOD
#define YVM_DEBUG_SHOW_CLASS_ATTRIBUTE
#endif


#endif // !YVM_OPTION_H

